// jobsdashboard-angular/src/app/components/view-jobs-applied/view-jobs-applied.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import axios from 'axios';


interface Job {
  _id: string;
  position: string;
  company: string;
  date_applied: Date;
  status: string;
  archive: boolean;
}

interface JobsAppliedType {
  _id: string;
  user_id: string;
  jobs_applied: Job[];
}

@Component({
  selector: 'app-view-jobs-applied',
  templateUrl: './view-jobs-applied.component.html',
  styleUrls: ['./view-jobs-applied.component.css']
})
export class ViewJobsAppliedComponent implements OnInit  {
  jobs_applied: JobsAppliedType[] = [];
  displayArchived = false;

  constructor(private router: Router) { }

  async ngOnInit() {
    await this.sendGetRequest();
  }

  async sendGetRequest() {
    try {
      const response = await axios.get('http://localhost:3001/api/jobsapplied');
      this.jobs_applied = response.data;
      console.log(response);
    } catch (err) {
      console.log(err);
    }
  }

  async handleArchive(user_id: string, job_id: string) {
    try {
      const response = await axios.patch(
        `http://localhost:3001/api/jobsapplied/${user_id}/${job_id}`,
        { archive: true }
      );
      console.log(response);
      await this.sendGetRequest();
    } catch (err) {
      console.log(err);
    }
  }

  goToJobs() {
    this.router.navigateByUrl('/jobs');
  }
}

<div class="place-content-center">
    <div class="ml-3 my-5">
        <a routerLink="/jobs" class="rounded bg-indigo-500 text-white py-2 px-4">Apply To Jobs</a>
        <button (click)="displayArchived = !displayArchived" class="{{displayArchived ? 'bg-green-500' : 'bg-red-500'}} text-white py-2 px-4 rounded">
            {{ displayArchived ? "Show Active Jobs" : "Show Archived Jobs" }}
        </button>
    </div>
    <h2 class="mt-5 text-center">Jobs Applied</h2>
    <ng-container *ngIf="jobs_applied.length > 0">
        <table class="mt-5 w-full text-md bg-white shadow-md rounded mb-4">
            <thead class="border-b">
                <tr>
                    <th class="text-left p-3 px-5">Job Title</th>
                    <th class="text-left p-3 px-5">Company Name</th>
                    <th class="text-left p-3 px-5">Date Applied</th>
                    <th class="text-left p-3 px-5">Status</th>
                    <th class="text-left p-3 px-5">Archive</th>
                </tr>
            </thead>
            <tbody>
                <ng-container *ngFor="let job of jobs_applied">
                    <app-jobs-applied-view
                        [user_id]="job.user_id"
                        [jobsApplied]="job.jobs_applied"
                        [displayArchived]="displayArchived"
                        >
                    </app-jobs-applied-view>
                </ng-container>
            </tbody>
        </table>
    </ng-container>
    <h1 class="noJobs text-center" *ngIf="jobs_applied.length === 0">Start applying to view your job applications here!!!</h1>
</div>

// jobsdashboard/src/components/Jobs/ViewJobsApplied.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import JobsAppliedView from '../../ui/JobsAppliedView'
import axios from 'axios';

type JobsAppliedType = {
    _id: string
    user_id: string;
    jobs_applied: [{
        _id: string;
        position: string;
        company: string;
        date_applied: Date;
        status: string;
        archive: boolean;
    }];
};

const ViewJobsApplied = () => {
	const [jobs_applied, setJobsApplied] = useState<JobsAppliedType[]>([]);
	const [displayArchived, setDisplayArchived] = useState<boolean>(false);

	const sendGetRequest = async () => {
    	try {
			const response = await axios.get(
				'http://localhost:3001/api/jobsapplied'
			);
			setJobsApplied(response.data);
			console.log(response);
		} catch (err) {
			console.log(err);
		}
	};

	const handleArchive = async (user_id: string, job_id: string) => {
		try {
			const response = await axios.patch(
				`http://localhost:3001/api/jobsapplied/${user_id}/${job_id}`,
				{ archive: true }
			);
			console.log(response);
			sendGetRequest();
		} catch (err) {
			console.log(err);
		}
	}

  	useEffect(() => {
		sendGetRequest();
  	}, []);

	return (
		<div className='place-content-center'>
			<div className='ml-3 my-5'>
				<Link to="/jobs" className=" rounded bg-indigo-500 text-white py-2 px-4 ">Apply To Jobs</Link>{" "}
				<button
					onClick={() => setDisplayArchived(!displayArchived)}
					className={`${ displayArchived ? 'bg-green-500': 'bg-red-500'} text-white py-2 px-4 rounded`}
				>{ displayArchived ? "Show Active Jobs" : "Show Archived Jobs" }</button>
			</div>
			{
				jobs_applied.length > 0 ? 
				jobs_applied.map((jobs_applied) => (
					<JobsAppliedView 
						key={jobs_applied._id}
						user_id={jobs_applied.user_id} 
						jobs_applied={jobs_applied.jobs_applied}
						displayArchived={displayArchived}
						handleArchive={handleArchive} 
					/>
				)) : <h1 className='noJobs text-center'>Start applying to view your job applications here!!!</h1>
			}

		</div>
	);
};

export default ViewJobsApplied;
