// jobsdashboard-angular/src/app/ui/jobs-applied-view/jobs-applied-view.component.ts
import { Component, Input } from '@angular/core';
import { faArchive } from '@fortawesome/free-solid-svg-icons';

type JobAppliedType = {
  _id: string;
  position: string;
  company: string;
  date_applied: Date;
  status: string;
  archive: boolean;
};

@Component({
  selector: 'app-jobs-applied-view',
  templateUrl: './jobs-applied-view.component.html',
  styleUrls: ['./jobs-applied-view.component.css']
})
export class JobsAppliedViewComponent {
  @Input() user_id!: string;
  @Input() jobsApplied!: JobAppliedType[];
  @Input() displayArchived!: boolean;
  faArchive = faArchive;

  handleArchive(user_id: string, job_id: string) {
    // handleArchive function logic here
  }
}

<tbody>
    <tr *ngFor="let job of jobsApplied" [hidden]="!((displayArchived && job.archive) || (!displayArchived && !job.archive))">
      <td class="border-grey-light border hover:bg-gray-100 p-3 px-5">{{ job.position }}</td>
      <td class="border-grey-light border hover:bg-gray-100 p-3 px-5">{{ job.company }}</td>
      <td class="border-grey-light border hover:bg-gray-100 p-3 px-5">{{ job.date_applied | date: 'shortDate' }}</td>
      <td class="border-grey-light border hover:bg-gray-100 p-3 px-5">{{ job.status }}</td>
      <td class="border-grey-light border hover:bg-gray-100 p-3 px-5">
        <button *ngIf="!job.archive" (click)="handleArchive(user_id, job._id)" class="{{ 'bg-red-500' }} text-white py-2 px-4 rounded">
          <fa-icon [icon]="faArchive"></fa-icon>
        </button>
      </td>
    </tr>
</tbody>

// jobsdashboard/src/ui/JobsAppliedView.tsx
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArchive } from '@fortawesome/free-solid-svg-icons';

type JobAppliedType = {
	_id: string;
	position: string;
	company: string;
	date_applied: Date;
	status: string;
	archive: boolean;
};

type JobsAppliedViewProps = {
	user_id: string;
	jobs_applied: JobAppliedType[];
	displayArchived: boolean;
	handleArchive: (user_id: string, job_id: string) => void;
};

const JobsAppliedView = ({
	user_id,
	jobs_applied,
	displayArchived,
	handleArchive,
}: JobsAppliedViewProps) => {
	return (
		<>
			<tbody>
				{jobs_applied.map((job) => (
					(displayArchived && job.archive) && <tr key={job._id}>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
							{job.position}
						</td>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
							{job.company}
						</td>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
							{new Date(job.date_applied).toLocaleDateString()}
						</td>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
							{job.status}
						</td>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
						{!job.archive && <button
								onClick={() => handleArchive(user_id, job._id)}
								className={`${
									'bg-red-500'
								} text-white py-2 px-4 rounded`}
							>
								<FontAwesomeIcon icon={faArchive} />
							</button>}
						</td>
					</tr>
				))}
				{jobs_applied.map((job) => (
					(!displayArchived && !job.archive) && <tr key={job._id}>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
							{job.position}
						</td>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
							{job.company}
						</td>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
							{new Date(job.date_applied).toLocaleDateString()}
						</td>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
							{job.status}
						</td>
						<td className='border-grey-light border hover:bg-gray-100 p-3 px-5'>
						{!job.archive && <button
								onClick={() => handleArchive(user_id, job._id)}
								className={`${
									'bg-red-500'
								} text-white py-2 px-4 rounded`}
							>
								<FontAwesomeIcon icon={faArchive} />
							</button>}
						</td>
					</tr>
				))}
			</tbody>
		</>
	);
};

export default JobsAppliedView;
